target-version = "py38"  # NOTE: inferred from pyproject.toml if present

lint.extend-select = [
    "F",   # flakes rules -- default, but extend just in case
    "E",   # pycodestyle  -- default, but extend just in case
    "C4",  # flake8-comprehensions -- unnecessary list/map/dict calls
    "UP",  # detect deprecated python stdlib stuff
    "FBT", # detect use of boolean arguments
]

lint.ignore = [
### too opinionated style checks
    "E501",  # too long lines
    "E702",  # Multiple statements on one line (semicolon)
    "E731",  # assigning lambda instead of using def
    "E741",  # Ambiguous variable name: `l`
    "E742",  # Ambiguous class name: `O
    "E401",  # Multiple imports on one line
    "F403",  # import *` used; unable to detect undefined names
###

###
    "E722",  # Do not use bare `except` ## Sometimes it's useful for defensive imports and that sort of thing..
    "F811",  # Redefinition of unused  # this gets in the way of pytest fixtures (e.g. in cachew)

## might be nice .. but later and I don't wanna make it strict
    "E402",  # Module level import not at top of file

### maybe consider these soon
# sometimes it's useful to give a variable a name even if we don't use it as a documentation
# on the other hand, often is a sign of error
    "F841",  # Local variable `count` is assigned to but never used
    "F401",  # imported but unused
###

### TODO should be fine to use these with from __future__ import annotations?
### there was some issue with cachew though... double check this?
    "UP006",  # use type instead of Type
    "UP007",  # use X | Y instead of Union
###
]
