#!/usr/bin/env python3
from datetime import datetime, timedelta

from rescuetime import get_rescuetime


def main():
    rs = get_rescuetime(latest=1)
    latest_dt = rs[-1].dt

    assert (datetime.now() - latest_dt) < timedelta(days=1)


if __name__ == '__main__':
    main()
