project:
  title: "HPI docs"
  render:
    - "*.qmd"  # otherwise picks up .md for some reason??
    - "README.qmd"  # for whatever reason quarto excludes it by default
format:
  gfm: default
  html: default
toc: true
toc-depth: 3
anchor-sections: true
# code-fold: true
execute:
  freeze: auto    # re-render only when source changes

# TODO ugh, index only can be generated in html/website mode
