* TOC
:PROPERTIES:
:TOC:      :include all :depth 3
:END:

:CONTENTS:
- [[#toc][TOC]]
- [[#running-tests][Running tests]]
- [[#ide-setup][IDE setup]]
- [[#linting][Linting]]
:END:

* Running tests
I'm using =tox= to run test/lint. You can check out [[file:../.github/workflows/main.yml][Github Actions]] config
and [[file:../scripts/ci/run]] for the up to date info on the specifics.

* IDE setup
To benefit from type hinting, make sure =my.config= is in your package search path.

In runtime, ~my.config~ is imported from the user config directory [[file:../src/my/core/init.py][dynamically]].

However, Pycharm/Emacs or whatever IDE you are using won't be able to figure that out, so you'd need to adjust your IDE configuration.

- Pycharm: basically, follow the instructions [[https://stackoverflow.com/a/55278260/706389][here]]

  i.e. create a new interpreter configuration (e.g. name it "Python 3.7 (for HPI)"), and add =~/.config/my=.

* Linting
~tox~ should run all test, mypy, etc.

If you want to run some specific parts/tests, consult [[file:tox.ini]].

Some useful flags (look them up):

- ~-e~ flag for tox
- ~-k~ flag for pytest
